### ISSUE TITLE
Agent form fields with pre-filled examples cannot be send as null

### ISSUE THREAD

**Issue by Jordi-m** [almende/eve-java#12]
I'm trying to use the agent webforms to send null values to the agent. With regular fields (string/int/etc) this works fine by just keeping that field empty (empty string). If the expected input type is a java object, the agent form fields are pre-fileld with an example structure. The purpose seems to be usefull.

However, I cannot really remove the default value for those java object examples. I can empty the form field and submit the form, but the java object example string is placed back into the form an submitted with the request. The results in not receiving the expected null value in the agent form.
## Steps to reproduce in screenshots:

I added the first couple of field manually (by default they are empty):
## ![2015-11-12 12_52_27-standby-dev_incident](https://cloud.githubusercontent.com/assets/4034848/11117713/81c46fca-893c-11e5-8ce9-d6b9debae82c.png)

... removed the default values for the java objects:
## ![2015-11-12 12_52_44-standby-dev_incident](https://cloud.githubusercontent.com/assets/4034848/11117714/81c67acc-893c-11e5-95a3-1bfa6cae77b6.png)

... submitted the form
## ![2015-11-12 12_52_57-standby-dev_incident](https://cloud.githubusercontent.com/assets/4034848/11117715/81c74df8-893c-11e5-85f6-a8021b51f4f5.png)

... default value showing up again in the form and in the JSON-RPC request
![2015-11-12 12_53_19-standby-dev_incident](https://cloud.githubusercontent.com/assets/4034848/11117716/81c8e578-893c-11e5-8b73-03ab3fc26452.png)

**Comment by ludost** [comment]
Fixed in Master.
