### ISSUE TITLE
No pubnub transport

### ISSUE THREAD

**Issue by georg90** [almende/eve-java#14]
Hi!

I use the nodejs implementation of eve.
There I successfully use pubnub to enable the agents to talk to each other.

Is there a way for pubnub on Android ?

**Comment by ludost** [comment]
Hi Georg,

Thanks for your interest. Currently the java version doesn't support Pubnub. Implementing it should be relative straightforward, tho. Let me see if I can find some time to work on it, as I have several transport feature requests I like to work on. Seems like a good match.

In most of our projects we connect the JS-Eve version to the Java version through websockets. It might also be interesting to see if that can be done the other way around as well: with an Android java client connecting to a JS-eve server side?

**Comment by georg90** [comment]
Hi Ludo!

I really appreciate if you'd find any time. I like to use it in an Android App, but since I want a distributed system without any servers I rely on pubnub for easy transportation :)

Are there any working examples of an Android App working with eve-java?

**Comment by ludost** [comment]
Hi George,

I did find some time:) Still very early work, I haven't actually tried it with the eve-js side yet, but in theory it should work. 

With regard to your other question: Sadly I have little off-the-shelf examples for Android. Biggest challenge is that Android seems to change every 3-5 months. :)  

Two example projects (highly undocumented!) can be found at:
https://github.com/almende/demoapps/tree/master/conferenceApp
https://github.com/almende/TuneSwarm/tree/master/TuneSwarmApp

That latest project was showing off distributed time synchronisation: https://www.youtube.com/watch?v=bGoe3CiQjOU&feature=youtu.be

I would still like to create a decent (stable!) example for Android, but currently I need to rediscover Android every time I look at it.....
